### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by GerhardLiebenberg** [yiiext/zend-autoloader-component#5]
Hi 

I'm trying to test zend email in a Yii "console" script.

The console command calls a behavior in common/extensions/behaviors/.... 

The behavior function has this code:
<b>Yii::import('common.extensions.EZendAutoloader', true);
EZendAutoloader::$prefixes = array('Zend');
EZendAutoloader::$basePath = Yii::getPathOfAlias('common.lib') . DIRECTORY_SEPARATOR;
Yii::registerAutoloader(array("EZendAutoloader", "loadClass"), true);</b>

This code works fine:
<b>$tr = new Zend_Mail_Transport_Sendmail('-freturn_to_me@example.com');
Zend_Mail::setDefaultTransport($tr);
$mail = new Zend_Mail();
$mail->setBodyText('This is the text of the mail.');
$mail->setFrom('somebody@example.com', 'Some Sender');
$mail->addTo('somebody_else@example.com', 'Some Recipient');
$mail->setSubject('TestSubject');
$mail->send();
</b>

But if I change the first row to:
<b>$tr = new Zend_Mail_Transport_Smtp('mail.example.com');</b>

Then this error follows:
<b>include(Zend/Validate/Hostname/Com.php): failed to open stream: 
No such file or directory (C:\xampp\htdocs\iccap\common\lib\Zend\Validate\Hostname.php:586)</b>

Line 586 of Hostname.php is:
<b>$regexChars += include($this->_validIdns[strtoupper($this->_tld)]);</b>

So it looks like this 'include' is not working. Any ideas?

**Comment by samdark** [comment]
Do you have that file?

**Comment by samdark** [comment]
Include should not be affected by autoload.

**Comment by GerhardLiebenberg** [comment]
Yes, I have the Zend/Validate/Hostname/Com.php file. I have the whole zend library included in Yii bootstrap.

**Comment by samdark** [comment]
Try adjusting your PHP include path. It doesn't seem to be related with autoloading at all.

**Comment by GerhardLiebenberg** [comment]
I have this:
Yii::setPathOfAlias('common', $root . DIRECTORY_SEPARATOR . 'common');
Yii::setPathOfAlias('Zend', $root . DIRECTORY_SEPARATOR . 'common' . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'Zend');

This works:
include('common/lib/Zend/Validate/Hostname/Com.php');

This throws the error:
include('Zend/Validate/Hostname/Com.php');

**Comment by samdark** [comment]
Yeah, that's include path of your PHP. You need to do `set_include_path('zend/library/dir'.get_include_path())`.

**Comment by GerhardLiebenberg** [comment]
Thank you Alexander

I had to do set_include_path('common/lib;' . get_include_path()) in the code - (note the semicolon after common/lib;)
  OR
I could add 'common.lib.*' to the 'import' array in config/main.php

I thought the problem was the last part of the path, but it was the first part of the path.
